CREATE TABLE IF NOT EXISTS public.firms
(
    firm_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    firm_name VARCHAR(128) NOT NULL UNIQUE,
    CONSTRAINT firm_pkey PRIMARY KEY (firm_id)
);